mkdir AwesomeApp
touch AwesomeApp/__init__.py
touch AwesomeApp/__main__.py
touch AwesomeApp/awesome.py 
touch AwesomeApp/readme.md
touch AwesomeApp/requirements.txt
touch AwesomeApp/some_module.py
mkdir AwesomeApp/package
touch AwesomeApp/package/__init__.py
touch AwesomeApp/package/package_module.py
